// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Neon.OpenApiClient.Projects.Item.Auth.Users.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Auth.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{projectId}\auth\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Neon.OpenApiClient.projects.item.auth.users.item collection</summary>
        /// <param name="position">The Neon user ID</param>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Auth.Users.Item.WithAuthUserItemRequestBuilder"/></returns>
        [Obsolete("")]
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Auth.Users.Item.WithAuthUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("authUserId", position);
                return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Auth.Users.Item.WithAuthUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Auth.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/auth/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Auth.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/auth/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
