// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Neon.OpenApiClient.Models;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Anonymize;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Anonymized_status;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Backup_schedule;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Compare_schema;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.DataApi;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Databases;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Endpoints;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Finalize_restore;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Masking_rules;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Recover;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Restore;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Roles;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Schema;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Set_as_default;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Snapshot;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project_id}\branches\{branch_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithBranch_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The anonymize property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Anonymize.AnonymizeRequestBuilder Anonymize
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Anonymize.AnonymizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The anonymized_status property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Anonymized_status.Anonymized_statusRequestBuilder Anonymized_status
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Anonymized_status.Anonymized_statusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthRequestBuilder Auth
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The backup_schedule property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Backup_schedule.Backup_scheduleRequestBuilder Backup_schedule
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Backup_schedule.Backup_scheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compare_schema property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Compare_schema.Compare_schemaRequestBuilder Compare_schema
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Compare_schema.Compare_schemaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataApi property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.DataApi.DataApiRequestBuilder DataApi
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.DataApi.DataApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The databases property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Databases.DatabasesRequestBuilder Databases
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Databases.DatabasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The endpoints property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Endpoints.EndpointsRequestBuilder Endpoints
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Endpoints.EndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The finalize_restore property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Finalize_restore.Finalize_restoreRequestBuilder Finalize_restore
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Finalize_restore.Finalize_restoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The masking_rules property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Masking_rules.Masking_rulesRequestBuilder Masking_rules
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Masking_rules.Masking_rulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recover property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Recover.RecoverRequestBuilder Recover
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Recover.RecoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Restore.RestoreRequestBuilder Restore
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Roles.RolesRequestBuilder Roles
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schema property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Schema.SchemaRequestBuilder Schema
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Schema.SchemaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The set_as_default property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Set_as_default.Set_as_defaultRequestBuilder Set_as_default
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Set_as_default.Set_as_defaultRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The snapshot property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Snapshot.SnapshotRequestBuilder Snapshot
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Snapshot.SnapshotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBranch_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/branches/{branch_id}{?hard_delete*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBranch_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/branches/{branch_id}{?hard_delete*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes the specified branch from a project, and placesall compute endpoints into an idle state, breaking existing client connections.You can obtain a `project_id` by listing the projects for your Neon account.You can obtain a `branch_id` by listing the project&apos;s branches.For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).When a successful response status is received, the compute endpoints are still active,and the branch is not yet deleted from storage.The deletion occurs after all operations finish.You cannot delete a project&apos;s root or default branch, and you cannot delete a branch that has a child branch.A project must have at least one branch.By default, deleted branches can be recovered within a 7-day grace period.Use the `hard_delete` parameter to permanently delete the branch immediately without a recovery window.Soft delete and branch recovery are in preview and not available to all users.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BranchOperations"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.BranchOperations?> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder.WithBranch_ItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.BranchOperations> DeleteAsync(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder.WithBranch_ItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Models.BranchOperations>(requestInfo, global::Soenneker.Neon.OpenApiClient.Models.BranchOperations.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves information about the specified branch.You can obtain a `project_id` by listing the projects for your Neon account.You can obtain a `branch_id` by listing the project&apos;s branches.A `branch_id` value has a `br-` prefix.Each Neon project is initially created with a root and default branch named `main`.A project can contain one or more branches.A parent branch is identified by a `parent_id` value, which is the `id` of the parent branch.For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_GetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_GetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_GetResponse>(requestInfo, global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the specified branch.You can obtain a `project_id` by listing the projects for your Neon account.You can obtain the `branch_id` by listing the project&apos;s branches.For more information, see [Manage branches](https://neon.tech/docs/manage/branches/).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BranchOperations"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.BranchOperations?> PatchAsync(global::Soenneker.Neon.OpenApiClient.Models.BranchUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.BranchOperations> PatchAsync(global::Soenneker.Neon.OpenApiClient.Models.BranchUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Models.BranchOperations>(requestInfo, global::Soenneker.Neon.OpenApiClient.Models.BranchOperations.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes the specified branch from a project, and placesall compute endpoints into an idle state, breaking existing client connections.You can obtain a `project_id` by listing the projects for your Neon account.You can obtain a `branch_id` by listing the project&apos;s branches.For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).When a successful response status is received, the compute endpoints are still active,and the branch is not yet deleted from storage.The deletion occurs after all operations finish.You cannot delete a project&apos;s root or default branch, and you cannot delete a branch that has a child branch.A project must have at least one branch.By default, deleted branches can be recovered within a 7-day grace period.Use the `hard_delete` parameter to permanently delete the branch immediately without a recovery window.Soft delete and branch recovery are in preview and not available to all users.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder.WithBranch_ItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder.WithBranch_ItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves information about the specified branch.You can obtain a `project_id` by listing the projects for your Neon account.You can obtain a `branch_id` by listing the project&apos;s branches.A `branch_id` value has a `br-` prefix.Each Neon project is initially created with a root and default branch named `main`.A project can contain one or more branches.A parent branch is identified by a `parent_id` value, which is the `id` of the parent branch.For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates the specified branch.You can obtain a `project_id` by listing the projects for your Neon account.You can obtain the `branch_id` by listing the project&apos;s branches.For more information, see [Manage branches](https://neon.tech/docs/manage/branches/).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.BranchUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.BranchUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.WithBranch_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Deletes the specified branch from a project, and placesall compute endpoints into an idle state, breaking existing client connections.You can obtain a `project_id` by listing the projects for your Neon account.You can obtain a `branch_id` by listing the project&apos;s branches.For related information, see [Manage branches](https://neon.tech/docs/manage/branches/).When a successful response status is received, the compute endpoints are still active,and the branch is not yet deleted from storage.The deletion occurs after all operations finish.You cannot delete a project&apos;s root or default branch, and you cannot delete a branch that has a child branch.A project must have at least one branch.By default, deleted branches can be recovered within a 7-day grace period.Use the `hard_delete` parameter to permanently delete the branch immediately without a recovery window.Soft delete and branch recovery are in preview and not available to all users.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBranch_ItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>If true, the branch is permanently deleted immediately without a recovery window.If false (default), the branch can be recovered within 7 days via the recover endpoint.This parameter is part of the Branch Recovery feature, which is in preview and not available to all users.</summary>
            [QueryParameter("hard_delete")]
            public bool? HardDelete { get; set; }
        }
    }
}
#pragma warning restore CS0618
