// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Neon.OpenApiClient.Models;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Allow_localhost;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Config;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Domains;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_and_password;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Oauth_providers;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Plugins;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Send_test_email;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Users;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project_id}\branches\{branch_id}\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allow_localhost property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Allow_localhost.Allow_localhostRequestBuilder Allow_localhost
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Allow_localhost.Allow_localhostRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Config.ConfigRequestBuilder Config
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The domains property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Domains.DomainsRequestBuilder Domains
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Domains.DomainsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email_and_password property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_and_password.Email_and_passwordRequestBuilder Email_and_password
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_and_password.Email_and_passwordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email_provider property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Email_providerRequestBuilder Email_provider
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Email_providerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth_providers property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Oauth_providers.Oauth_providersRequestBuilder Oauth_providers
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Oauth_providers.Oauth_providersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plugins property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send_test_email property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Send_test_email.Send_test_emailRequestBuilder Send_test_email
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Send_test_email.Send_test_emailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/branches/{branch_id}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/branches/{branch_id}/auth", rawUrl)
        {
        }
        /// <summary>
        /// Disables Neon Auth for the branch
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// / Fetches the details of the Neon Auth for the specified branch. You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon account.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.NeonAuthIntegration"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthIntegration?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthIntegration> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthIntegration>(requestInfo, global::Soenneker.Neon.OpenApiClient.Models.NeonAuthIntegration.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Enables Neon Auth integrationfor the branch.You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon account.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.NeonAuthCreateIntegrationResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthCreateIntegrationResponse?> PostAsync(global::Soenneker.Neon.OpenApiClient.Models.EnableNeonAuthIntegrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthCreateIntegrationResponse> PostAsync(global::Soenneker.Neon.OpenApiClient.Models.EnableNeonAuthIntegrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthCreateIntegrationResponse>(requestInfo, global::Soenneker.Neon.OpenApiClient.Models.NeonAuthCreateIntegrationResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Disables Neon Auth for the branch
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// / Fetches the details of the Neon Auth for the specified branch. You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon account.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Enables Neon Auth integrationfor the branch.You can obtain the `project_id` and `branch_id` by listing the projects and branches for your Neon account.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.EnableNeonAuthIntegrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.EnableNeonAuthIntegrationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.AuthRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
