// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Neon.OpenApiClient.Models;
using Soenneker.Neon.OpenApiClient.Projects.Auth;
using Soenneker.Neon.OpenApiClient.Projects.Item;
using Soenneker.Neon.OpenApiClient.Projects.Shared;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects
{
    /// <summary>
    /// Builds and executes requests for operations under \projects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Auth.AuthRequestBuilder Auth
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shared property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Shared.SharedRequestBuilder Shared
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Shared.SharedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Neon.OpenApiClient.projects.item collection</summary>
        /// <param name="position">The Neon project ID</param>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.WithProject_ItemRequestBuilder"/></returns>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.WithProject_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("project_id", position);
                return new global::Soenneker.Neon.OpenApiClient.Projects.Item.WithProject_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects{?cursor*,limit*,org_id*,recoverable*,search*,timeout*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects{?cursor*,limit*,org_id*,recoverable*,search*,timeout*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a list of projects for an organization.You may need to specify an org_id parameter depending on your API key type.For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.ProjectsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsGetResponse>(requestInfo, global::Soenneker.Neon.OpenApiClient.Projects.ProjectsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a Neon project within an organization.You may need to specify an org_id parameter depending on your API key type.Plan limits define how many projects you can create.For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).You can specify a region and Postgres version in the request body.Neon currently supports PostgreSQL 14, 15, 16, and 17.For supported regions and `region_id` values, see [Regions](https://neon.tech/docs/introduction/regions/).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.ProjectsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsPostResponse?> PostAsync(global::Soenneker.Neon.OpenApiClient.Models.ProjectCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsPostResponse> PostAsync(global::Soenneker.Neon.OpenApiClient.Models.ProjectCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsPostResponse>(requestInfo, global::Soenneker.Neon.OpenApiClient.Projects.ProjectsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a list of projects for an organization.You may need to specify an org_id parameter depending on your API key type.For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a Neon project within an organization.You may need to specify an org_id parameter depending on your API key type.Plan limits define how many projects you can create.For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).You can specify a region and Postgres version in the request body.Neon currently supports PostgreSQL 14, 15, 16, and 17.For supported regions and `region_id` values, see [Regions](https://neon.tech/docs/introduction/regions/).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.ProjectCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.ProjectCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Neon.OpenApiClient.Projects.ProjectsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a list of projects for an organization.You may need to specify an org_id parameter depending on your API key type.For more information, see [Manage projects](https://neon.tech/docs/manage/projects/).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsRequestBuilderGetQueryParameters 
        {
            /// <summary>Specify the cursor value from the previous response to retrieve the next batch of projects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Specify a value from 1 to 400 to limit number of projects in the response.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Search for projects by `org_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("org_id")]
            public string? OrgId { get; set; }
#nullable restore
#else
            [QueryParameter("org_id")]
            public string OrgId { get; set; }
#endif
            /// <summary>Show only deleted projects within the recovery window.</summary>
            [QueryParameter("recoverable")]
            public bool? Recoverable { get; set; }
            /// <summary>Search by project `name` or `id`. You can specify partial `name` or `id` values to filter results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Specify an explicit timeout in milliseconds to limit response delay.After timing out, the incomplete list of project data fetched so far will be returned.Projects still being fetched when the timeout occurred are listed in the &quot;unavailable&quot; attribute of the response.If not specified, an implicit implementation defined timeout is chosen with the same behaviour as above</summary>
            [QueryParameter("timeout")]
            public int? Timeout { get; set; }
        }
    }
}
#pragma warning restore CS0618
