// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Branches
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BranchesPostRequestBody_branch : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to create the branch as archived</summary>
        public bool? Archived { get; set; }
        /// <summary>The timestamp when the branch is scheduled to expire and be automatically deleted. Must be set by the client following the [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6) format with precision up to seconds (such as 2025-06-09T18:02:16Z). Deletion is performed by a background job and may not occur exactly at the specified time.Access to this feature is currently limited to participants in the Early Access Program.</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The source of initialization for the branch. Valid values are `schema-only` and `parent-data` (default).  * `schema-only` - creates a new root branch containing only the schema. Use `parent_id` to specify the source branch. Optionally, you can provide `parent_lsn` or `parent_timestamp` to branch from a specific point in time or LSN. These fields define which branch to copy the schema from and at what point—they do not establish a parent-child relationship between the `parent_id` branch and the new schema-only branch.  * `parent-data` - creates the branch with both schema and data from the parent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitSource { get; set; }
#nullable restore
#else
        public string InitSource { get; set; }
#endif
        /// <summary>The branch name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The `branch_id` of the parent branch. If omitted or empty, the branch will be created from the project&apos;s default branch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentId { get; set; }
#nullable restore
#else
        public string ParentId { get; set; }
#endif
        /// <summary>A Log Sequence Number (LSN) on the parent branch. The branch will be created with data from this LSN.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentLsn { get; set; }
#nullable restore
#else
        public string ParentLsn { get; set; }
#endif
        /// <summary>A timestamp identifying a point in time on the parent branch. The branch will be created with data starting from this point in time.The timestamp must be provided in ISO 8601 format; for example: `2024-02-26T12:00:00Z`.</summary>
        public DateTimeOffset? ParentTimestamp { get; set; }
        /// <summary>Whether the branch is protected</summary>
        public bool? Protected { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.BranchesPostRequestBody_branch"/> and sets the default values.
        /// </summary>
        public BranchesPostRequestBody_branch()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.BranchesPostRequestBody_branch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.BranchesPostRequestBody_branch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.BranchesPostRequestBody_branch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "init_source", n => { InitSource = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent_id", n => { ParentId = n.GetStringValue(); } },
                { "parent_lsn", n => { ParentLsn = n.GetStringValue(); } },
                { "parent_timestamp", n => { ParentTimestamp = n.GetDateTimeOffsetValue(); } },
                { "protected", n => { Protected = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteStringValue("init_source", InitSource);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("parent_id", ParentId);
            writer.WriteStringValue("parent_lsn", ParentLsn);
            writer.WriteDateTimeOffsetValue("parent_timestamp", ParentTimestamp);
            writer.WriteBoolValue("protected", Protected);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
