// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Neon.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Snapshots.Item.Restore
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RestorePostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.Branch? Branch { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.Branch Branch { get; set; }
#endif
        /// <summary>The endpoints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.Endpoint>? Endpoints { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.Endpoint> Endpoints { get; set; }
#endif
        /// <summary>The operations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.Operation>? Operations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.Operation> Operations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Snapshots.Item.Restore.RestorePostResponse"/> and sets the default values.
        /// </summary>
        public RestorePostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Snapshots.Item.Restore.RestorePostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Projects.Item.Snapshots.Item.Restore.RestorePostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Snapshots.Item.Restore.RestorePostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branch", n => { Branch = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.Branch>(global::Soenneker.Neon.OpenApiClient.Models.Branch.CreateFromDiscriminatorValue); } },
                { "endpoints", n => { Endpoints = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.Endpoint>(global::Soenneker.Neon.OpenApiClient.Models.Endpoint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "operations", n => { Operations = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.Operation>(global::Soenneker.Neon.OpenApiClient.Models.Operation.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.Branch>("branch", Branch);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.Endpoint>("endpoints", Endpoints);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.Operation>("operations", Operations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
