// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Neon.OpenApiClient.Models;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.Objects;
using Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.ObjectsByPrefix;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{projectId}\branches\{branchId}\buckets\{bucketName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithBucketNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The objects property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.Objects.ObjectsRequestBuilder Objects
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.Objects.ObjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The objectsByPrefix property</summary>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.ObjectsByPrefix.ObjectsByPrefixRequestBuilder ObjectsByPrefix
        {
            get => new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.ObjectsByPrefix.ObjectsByPrefixRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.WithBucketNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBucketNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/branches/{branchId}/buckets/{bucketName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.WithBucketNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBucketNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/branches/{branchId}/buckets/{bucketName}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Deletes the named bucket from the specified branch.**Note**: This endpoint is currently in Private Beta.&quot;
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Deletes the named bucket from the specified branch.**Note**: This endpoint is currently in Private Beta.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.WithBucketNameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.WithBucketNameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Buckets.Item.WithBucketNameItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
