// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Neon.OpenApiClient.Models;
using Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project_id}\transfer_requests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Transfer_requestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Neon.OpenApiClient.projects.item.transfer_requests.item collection</summary>
        /// <param name="position">The Neon project transfer request ID</param>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Item.WithRequest_ItemRequestBuilder"/></returns>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Item.WithRequest_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("request_id", position);
                return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Item.WithRequest_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Transfer_requestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/transfer_requests", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Transfer_requestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/transfer_requests", rawUrl)
        {
        }
        /// <summary>
        /// Creates a transfer request for the specified project. A transfer request allowsthe project to be transferred to another account or organization. The requesthas an expiration time after which it can no longer be used. To accept/claimthe transfer request, the recipient user/organization must call the`/projects/{project_id}/transfer_requests/{request_id}` API endpoint, or visit`https://console.neon.tech/app/claim?p={project_id}&amp;tr={request_id}&amp;ru={redirect_url}`in the Neon Console. The `ru` parameter is optional and can be used to redirectthe user after accepting the transfer request.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.ProjectTransferRequestResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.ProjectTransferRequestResponse?> PostAsync(global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.ProjectTransferRequestResponse> PostAsync(global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Models.ProjectTransferRequestResponse>(requestInfo, global::Soenneker.Neon.OpenApiClient.Models.ProjectTransferRequestResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a transfer request for the specified project. A transfer request allowsthe project to be transferred to another account or organization. The requesthas an expiration time after which it can no longer be used. To accept/claimthe transfer request, the recipient user/organization must call the`/projects/{project_id}/transfer_requests/{request_id}` API endpoint, or visit`https://console.neon.tech/app/claim?p={project_id}&amp;tr={request_id}&amp;ru={redirect_url}`in the Neon Console. The `ru` parameter is optional and can be used to redirectthe user after accepting the transfer request.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Transfer_requests.Transfer_requestsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
