// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>Category of an advisor issue</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdvisorCategory
    {
        [EnumMember(Value = "SECURITY")]
        #pragma warning disable CS1591
        SECURITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERFORMANCE")]
        #pragma warning disable CS1591
        PERFORMANCE,
        #pragma warning restore CS1591
    }
}
