// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>Whether this issue affects external API exposure or is internal only</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AdvisorIssue_facing
    {
        [EnumMember(Value = "EXTERNAL")]
        #pragma warning disable CS1591
        EXTERNAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTERNAL")]
        #pragma warning disable CS1591
        INTERNAL,
        #pragma warning restore CS1591
    }
}
