// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AnonymizedBranchStatusResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the anonymized branch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BranchId { get; set; }
#nullable restore
#else
        public string BranchId { get; set; }
#endif
        /// <summary>A timestamp indicating when the anonymized branch was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>A timestamp indicating when the anonymized branch operation failed (if applicable)</summary>
        public DateTimeOffset? FailedAt { get; set; }
        /// <summary>Metadata about the most recent anonymization attempt for the branch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.AnonymizationRunMetadata? LastRun { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.AnonymizationRunMetadata LastRun { get; set; }
#endif
        /// <summary>The ID of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The current state of the anonymized branch. Possible values: created, initialized, initialization_error, anonymizing, anonymized, error</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>A descriptive message about the current status or any errors</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusMessage { get; set; }
#nullable restore
#else
        public string StatusMessage { get; set; }
#endif
        /// <summary>A timestamp indicating when the anonymized branch status was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.AnonymizedBranchStatusResponse"/> and sets the default values.
        /// </summary>
        public AnonymizedBranchStatusResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.AnonymizedBranchStatusResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.AnonymizedBranchStatusResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.AnonymizedBranchStatusResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branch_id", n => { BranchId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "failed_at", n => { FailedAt = n.GetDateTimeOffsetValue(); } },
                { "last_run", n => { LastRun = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.AnonymizationRunMetadata>(global::Soenneker.Neon.OpenApiClient.Models.AnonymizationRunMetadata.CreateFromDiscriminatorValue); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "status_message", n => { StatusMessage = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("branch_id", BranchId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("failed_at", FailedAt);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.AnonymizationRunMetadata>("last_run", LastRun);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("status_message", StatusMessage);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
