// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BackupScheduleItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The day of the week or month to take the snapshot (if applicable).</summary>
        public int? Day { get; set; }
        /// <summary>How often to take snapshots. Must be one of the following values:  - `hourly`  - `daily`  - `weekly`  - `monthly`  - `yearly`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Frequency { get; set; }
#nullable restore
#else
        public string Frequency { get; set; }
#endif
        /// <summary>The hour of the day to take the snapshot (if applicable).</summary>
        public int? Hour { get; set; }
        /// <summary>The month of the year to take the snapshot (if applicable).</summary>
        public int? Month { get; set; }
        /// <summary>How long to keep a snapshot (in seconds) before it&apos;s automatically deleted.If not set, the snapshot is kept indefinitely.</summary>
        public int? RetentionSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.BackupScheduleItem"/> and sets the default values.
        /// </summary>
        public BackupScheduleItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BackupScheduleItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.BackupScheduleItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.BackupScheduleItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "day", n => { Day = n.GetIntValue(); } },
                { "frequency", n => { Frequency = n.GetStringValue(); } },
                { "hour", n => { Hour = n.GetIntValue(); } },
                { "month", n => { Month = n.GetIntValue(); } },
                { "retention_seconds", n => { RetentionSeconds = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("day", Day);
            writer.WriteStringValue("frequency", Frequency);
            writer.WriteIntValue("hour", Hour);
            writer.WriteIntValue("month", Month);
            writer.WriteIntValue("retention_seconds", RetentionSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
