// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BillingAccount : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Billing address city.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressCity { get; set; }
#nullable restore
#else
        public string AddressCity { get; set; }
#endif
        /// <summary>Billing address country code defined by ISO 3166-1 alpha-2.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressCountry { get; set; }
#nullable restore
#else
        public string AddressCountry { get; set; }
#endif
        /// <summary>Billing address country name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressCountryName { get; set; }
#nullable restore
#else
        public string AddressCountryName { get; set; }
#endif
        /// <summary>Billing address line 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine1 { get; set; }
#nullable restore
#else
        public string AddressLine1 { get; set; }
#endif
        /// <summary>Billing address line 2.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine2 { get; set; }
#nullable restore
#else
        public string AddressLine2 { get; set; }
#endif
        /// <summary>Billing address postal code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressPostalCode { get; set; }
#nullable restore
#else
        public string AddressPostalCode { get; set; }
#endif
        /// <summary>Billing address state or region.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressState { get; set; }
#nullable restore
#else
        public string AddressState { get; set; }
#endif
        /// <summary>Billing email, to receive emails related to invoices and subscriptions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The full name of the individual or entity that owns the billing account. This name appears on invoices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Orb user portal url</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrbPortalUrl { get; set; }
#nullable restore
#else
        public string OrbPortalUrl { get; set; }
#endif
        /// <summary>Indicates whether and how an account makes payments.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.BillingPaymentMethod? PaymentMethod { get; set; }
        /// <summary>The payment_source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.PaymentSource? PaymentSource { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.PaymentSource PaymentSource { get; set; }
#endif
        /// <summary>The plan_details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.PlanDetails? PlanDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.PlanDetails PlanDetails { get; set; }
#endif
        /// <summary>The last time the quota was reset. Defaults to the date-time the account is created.</summary>
        public DateTimeOffset? QuotaResetAtLast { get; set; }
        /// <summary>Monthly spending cap in cents for V3 paid plans. When set,notifications are sent at 80% and 100% of this limit. `null`means no limit is configured.</summary>
        public long? SpendingLimitCents { get; set; }
        /// <summary>State of the billing account.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.BillingAccountState? State { get; set; }
        /// <summary>Type of subscription to Neon Cloud.Notice that for users without billing account this will be &quot;UNKNOWN&quot;</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.BillingSubscriptionType? SubscriptionType { get; set; }
        /// <summary>The tax identification number for the billing account, displayed on invoices.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxId { get; set; }
#nullable restore
#else
        public string TaxId { get; set; }
#endif
        /// <summary>The type of the tax identification number based on the country.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaxIdType { get; set; }
#nullable restore
#else
        public string TaxIdType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.BillingAccount"/> and sets the default values.
        /// </summary>
        public BillingAccount()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BillingAccount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.BillingAccount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.BillingAccount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address_city", n => { AddressCity = n.GetStringValue(); } },
                { "address_country", n => { AddressCountry = n.GetStringValue(); } },
                { "address_country_name", n => { AddressCountryName = n.GetStringValue(); } },
                { "address_line1", n => { AddressLine1 = n.GetStringValue(); } },
                { "address_line2", n => { AddressLine2 = n.GetStringValue(); } },
                { "address_postal_code", n => { AddressPostalCode = n.GetStringValue(); } },
                { "address_state", n => { AddressState = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orb_portal_url", n => { OrbPortalUrl = n.GetStringValue(); } },
                { "payment_method", n => { PaymentMethod = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.BillingPaymentMethod>(); } },
                { "payment_source", n => { PaymentSource = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PaymentSource>(global::Soenneker.Neon.OpenApiClient.Models.PaymentSource.CreateFromDiscriminatorValue); } },
                { "plan_details", n => { PlanDetails = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PlanDetails>(global::Soenneker.Neon.OpenApiClient.Models.PlanDetails.CreateFromDiscriminatorValue); } },
                { "quota_reset_at_last", n => { QuotaResetAtLast = n.GetDateTimeOffsetValue(); } },
                { "spending_limit_cents", n => { SpendingLimitCents = n.GetLongValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.BillingAccountState>(); } },
                { "subscription_type", n => { SubscriptionType = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.BillingSubscriptionType>(); } },
                { "tax_id", n => { TaxId = n.GetStringValue(); } },
                { "tax_id_type", n => { TaxIdType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address_city", AddressCity);
            writer.WriteStringValue("address_country", AddressCountry);
            writer.WriteStringValue("address_country_name", AddressCountryName);
            writer.WriteStringValue("address_line1", AddressLine1);
            writer.WriteStringValue("address_line2", AddressLine2);
            writer.WriteStringValue("address_postal_code", AddressPostalCode);
            writer.WriteStringValue("address_state", AddressState);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("orb_portal_url", OrbPortalUrl);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.BillingPaymentMethod>("payment_method", PaymentMethod);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PaymentSource>("payment_source", PaymentSource);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PlanDetails>("plan_details", PlanDetails);
            writer.WriteDateTimeOffsetValue("quota_reset_at_last", QuotaResetAtLast);
            writer.WriteLongValue("spending_limit_cents", SpendingLimitCents);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.BillingAccountState>("state", State);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.BillingSubscriptionType>("subscription_type", SubscriptionType);
            writer.WriteStringValue("tax_id", TaxId);
            writer.WriteStringValue("tax_id_type", TaxIdType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
