// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>Type of subscription to Neon Cloud.Notice that for users without billing account this will be &quot;UNKNOWN&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BillingSubscriptionType
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "direct_sales")]
        #pragma warning disable CS1591
        DirectSales,
        #pragma warning restore CS1591
        [EnumMember(Value = "direct_sales_v3")]
        #pragma warning disable CS1591
        DirectSalesV3,
        #pragma warning restore CS1591
        [EnumMember(Value = "aws_marketplace")]
        #pragma warning disable CS1591
        AwsMarketplace,
        #pragma warning restore CS1591
        [EnumMember(Value = "free_v2")]
        #pragma warning disable CS1591
        FreeV2,
        #pragma warning restore CS1591
        [EnumMember(Value = "free_v3")]
        #pragma warning disable CS1591
        FreeV3,
        #pragma warning restore CS1591
        [EnumMember(Value = "launch")]
        #pragma warning disable CS1591
        Launch,
        #pragma warning restore CS1591
        [EnumMember(Value = "launch_v3")]
        #pragma warning disable CS1591
        LaunchV3,
        #pragma warning restore CS1591
        [EnumMember(Value = "scale")]
        #pragma warning disable CS1591
        Scale,
        #pragma warning restore CS1591
        [EnumMember(Value = "scale_v3")]
        #pragma warning disable CS1591
        ScaleV3,
        #pragma warning restore CS1591
        [EnumMember(Value = "business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
        [EnumMember(Value = "vercel_pg_legacy")]
        #pragma warning disable CS1591
        VercelPgLegacy,
        #pragma warning restore CS1591
    }
}
