// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Branch : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active_time_seconds property</summary>
        public long? ActiveTimeSeconds { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The compute_time_seconds property</summary>
        public long? ComputeTimeSeconds { get; set; }
        /// <summary>CPU seconds used by all of the branch&apos;s compute endpoints, including deleted ones.This value is reset at the beginning of each billing period.Examples:1. A branch that uses 1 CPU for 1 second is equal to `cpu_used_sec=1`.2. A branch that uses 2 CPUs simultaneously for 1 second is equal to `cpu_used_sec=2`.</summary>
        [Obsolete("")]
        public long? CpuUsedSec { get; set; }
        /// <summary>A timestamp indicating when the branch was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The resolved user model that contains details of the user/org/integration/api_key used for branch creation. This field is filled only in listing/get/create/get/update/delete methods, if it is empty when calling other handlers, it does not mean that it is empty in the system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.Branch_created_by? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.Branch_created_by CreatedBy { get; set; }
#endif
        /// <summary>The branch creation source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreationSource { get; set; }
#nullable restore
#else
        public string CreationSource { get; set; }
#endif
        /// <summary>The branch’s state, indicating if it is initializing, ready for use, or archived.  * &apos;init&apos; - the branch is being created but is not available for querying.  * &apos;resetting&apos; - the branch is being reset to a specific point in time or LSN and is not yet available for querying.  * &apos;ready&apos; - the branch is fully operational and ready for querying. Expect normal query response times.  * &apos;archived&apos; - the branch is stored in cost-effective archival storage. Expect slow query response times.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentState { get; set; }
#nullable restore
#else
        public string CurrentState { get; set; }
#endif
        /// <summary>The data_transfer_bytes property</summary>
        public long? DataTransferBytes { get; set; }
        /// <summary>Whether the branch is the project&apos;s default branch</summary>
        public bool? Default { get; set; }
        /// <summary>The timestamp when the branch is scheduled to expire and be automatically deleted. Must be set by the client following the [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6) format with precision up to seconds (such as 2025-06-09T18:02:16Z). Deletion is performed by a background job and may not occur exactly at the specified time.Access to this feature is currently limited to participants in the Early Access Program.</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The branch ID. This value is generated when a branch is created. A `branch_id` value has a `br` prefix. For example: `br-small-term-683261`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The source of initialization for the branch. Valid values are `schema-only` and `parent-data` (default).  * `schema-only` - creates a new root branch containing only the schema. Use `parent_id` to specify the source branch. Optionally, you can provide `parent_lsn` or `parent_timestamp` to branch from a specific point in time or LSN. These fields define which branch to copy the schema from and at what point—they do not establish a parent-child relationship between the `parent_id` branch and the new schema-only branch.  * `parent-data` - creates the branch with both schema and data from the parent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitSource { get; set; }
#nullable restore
#else
        public string InitSource { get; set; }
#endif
        /// <summary>A timestamp indicating when the branch was last reset</summary>
        public DateTimeOffset? LastResetAt { get; set; }
        /// <summary>The logical size of the branch, in bytes</summary>
        public long? LogicalSize { get; set; }
        /// <summary>The branch name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The `branch_id` of the parent branch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentId { get; set; }
#nullable restore
#else
        public string ParentId { get; set; }
#endif
        /// <summary>The Log Sequence Number (LSN) on the parent branch from which this branch was created.When restoring a branch using the [Restore branch](https://api-docs.neon.tech/reference/restoreprojectbranch) endpoint,this value isn’t finalized until all operations related to the restore have completed successfully.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentLsn { get; set; }
#nullable restore
#else
        public string ParentLsn { get; set; }
#endif
        /// <summary>The point in time on the parent branch from which this branch was created.When restoring a branch using the [Restore branch](https://api-docs.neon.tech/reference/restoreprojectbranch) endpoint,this value isn’t finalized until all operations related to the restore have completed successfully.After all the operations completed, this value might stay empty.</summary>
        public DateTimeOffset? ParentTimestamp { get; set; }
        /// <summary>The branch’s state, indicating if it is initializing, ready for use, or archived.  * &apos;init&apos; - the branch is being created but is not available for querying.  * &apos;resetting&apos; - the branch is being reset to a specific point in time or LSN and is not yet available for querying.  * &apos;ready&apos; - the branch is fully operational and ready for querying. Expect normal query response times.  * &apos;archived&apos; - the branch is stored in cost-effective archival storage. Expect slow query response times.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PendingState { get; set; }
#nullable restore
#else
        public string PendingState { get; set; }
#endif
        /// <summary>DEPRECATED. Use `default` field.Whether the branch is the project&apos;s primary branch</summary>
        [Obsolete("")]
        public bool? Primary { get; set; }
        /// <summary>The ID of the project to which the branch belongs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>Whether the branch is protected</summary>
        public bool? Protected { get; set; }
        /// <summary>Recovery information for a deleted branch. Only present when listing deleted brancheswith `include_deleted=true`.This is part of the Branch Recovery feature, which is in preview and not available to all users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.BranchRecoveryInfo? Recovery { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.BranchRecoveryInfo Recovery { get; set; }
#endif
        /// <summary>ID of the target branch which was replaced when this branch was restored</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RestoredAs { get; set; }
#nullable restore
#else
        public string RestoredAs { get; set; }
#endif
        /// <summary>ID of the snapshot that was the restore source for this branch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RestoredFrom { get; set; }
#nullable restore
#else
        public string RestoredFrom { get; set; }
#endif
        /// <summary>Could be `restored`, `finalized` or `detaching`.A `restored` branch becomes permanently `finalized` when you call `finalizeRestoreBranch`A `restored` or `finalized` branch may begin `detaching` as a one-time performance optimisation, after which it will continue in its original state</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RestoreStatus { get; set; }
#nullable restore
#else
        public string RestoreStatus { get; set; }
#endif
        /// <summary>A list of actions that are currently restricted for this branch and the reason why.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.BranchRestrictedAction>? RestrictedActions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.BranchRestrictedAction> RestrictedActions { get; set; }
#endif
        /// <summary>A UTC timestamp indicating when the `current_state` began</summary>
        public DateTimeOffset? StateChangedAt { get; set; }
        /// <summary>The time-to-live (TTL) duration originally configured for the branch, in seconds. This read-only value represents the interval between the time `expires_at` was set and the expiration timestamp itself. It is preserved to ensure the same TTL duration is reapplied when resetting the branch from its parent, and only updates when a new `expires_at` value is set.Access to this feature is currently limited to participants in the Early Access Program.</summary>
        public int? TtlIntervalSeconds { get; set; }
        /// <summary>A timestamp indicating when the branch was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The written_data_bytes property</summary>
        public long? WrittenDataBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.Branch"/> and sets the default values.
        /// </summary>
        public Branch()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.Branch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.Branch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.Branch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_time_seconds", n => { ActiveTimeSeconds = n.GetLongValue(); } },
                { "compute_time_seconds", n => { ComputeTimeSeconds = n.GetLongValue(); } },
                { "cpu_used_sec", n => { CpuUsedSec = n.GetLongValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.Branch_created_by>(global::Soenneker.Neon.OpenApiClient.Models.Branch_created_by.CreateFromDiscriminatorValue); } },
                { "creation_source", n => { CreationSource = n.GetStringValue(); } },
                { "current_state", n => { CurrentState = n.GetStringValue(); } },
                { "data_transfer_bytes", n => { DataTransferBytes = n.GetLongValue(); } },
                { "default", n => { Default = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "init_source", n => { InitSource = n.GetStringValue(); } },
                { "last_reset_at", n => { LastResetAt = n.GetDateTimeOffsetValue(); } },
                { "logical_size", n => { LogicalSize = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent_id", n => { ParentId = n.GetStringValue(); } },
                { "parent_lsn", n => { ParentLsn = n.GetStringValue(); } },
                { "parent_timestamp", n => { ParentTimestamp = n.GetDateTimeOffsetValue(); } },
                { "pending_state", n => { PendingState = n.GetStringValue(); } },
                { "primary", n => { Primary = n.GetBoolValue(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "protected", n => { Protected = n.GetBoolValue(); } },
                { "recovery", n => { Recovery = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.BranchRecoveryInfo>(global::Soenneker.Neon.OpenApiClient.Models.BranchRecoveryInfo.CreateFromDiscriminatorValue); } },
                { "restore_status", n => { RestoreStatus = n.GetStringValue(); } },
                { "restored_as", n => { RestoredAs = n.GetStringValue(); } },
                { "restored_from", n => { RestoredFrom = n.GetStringValue(); } },
                { "restricted_actions", n => { RestrictedActions = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BranchRestrictedAction>(global::Soenneker.Neon.OpenApiClient.Models.BranchRestrictedAction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "state_changed_at", n => { StateChangedAt = n.GetDateTimeOffsetValue(); } },
                { "ttl_interval_seconds", n => { TtlIntervalSeconds = n.GetIntValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "written_data_bytes", n => { WrittenDataBytes = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("active_time_seconds", ActiveTimeSeconds);
            writer.WriteLongValue("compute_time_seconds", ComputeTimeSeconds);
            writer.WriteLongValue("cpu_used_sec", CpuUsedSec);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.Branch_created_by>("created_by", CreatedBy);
            writer.WriteStringValue("creation_source", CreationSource);
            writer.WriteStringValue("current_state", CurrentState);
            writer.WriteLongValue("data_transfer_bytes", DataTransferBytes);
            writer.WriteBoolValue("default", Default);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("init_source", InitSource);
            writer.WriteDateTimeOffsetValue("last_reset_at", LastResetAt);
            writer.WriteLongValue("logical_size", LogicalSize);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("parent_id", ParentId);
            writer.WriteStringValue("parent_lsn", ParentLsn);
            writer.WriteDateTimeOffsetValue("parent_timestamp", ParentTimestamp);
            writer.WriteStringValue("pending_state", PendingState);
            writer.WriteBoolValue("primary", Primary);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteBoolValue("protected", Protected);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.BranchRecoveryInfo>("recovery", Recovery);
            writer.WriteStringValue("restored_as", RestoredAs);
            writer.WriteStringValue("restored_from", RestoredFrom);
            writer.WriteStringValue("restore_status", RestoreStatus);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BranchRestrictedAction>("restricted_actions", RestrictedActions);
            writer.WriteDateTimeOffsetValue("state_changed_at", StateChangedAt);
            writer.WriteIntValue("ttl_interval_seconds", TtlIntervalSeconds);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteLongValue("written_data_bytes", WrittenDataBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
