// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BranchAnonymizedCreateRequest : global::Soenneker.Neon.OpenApiClient.Models.AnnotationCreateValueRequest, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The branch_create property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.BranchCreateRequest? BranchCreate { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.BranchCreateRequest BranchCreate { get; set; }
#endif
        /// <summary>List of masking rules to apply to the branch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.MaskingRule>? MaskingRules { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.MaskingRule> MaskingRules { get; set; }
#endif
        /// <summary>If true, automatically start anonymization after the branch is created.Defaults to false.</summary>
        public bool? StartAnonymization { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BranchAnonymizedCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Neon.OpenApiClient.Models.BranchAnonymizedCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.BranchAnonymizedCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "branch_create", n => { BranchCreate = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.BranchCreateRequest>(global::Soenneker.Neon.OpenApiClient.Models.BranchCreateRequest.CreateFromDiscriminatorValue); } },
                { "masking_rules", n => { MaskingRules = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.MaskingRule>(global::Soenneker.Neon.OpenApiClient.Models.MaskingRule.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_anonymization", n => { StartAnonymization = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.BranchCreateRequest>("branch_create", BranchCreate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.MaskingRule>("masking_rules", MaskingRules);
            writer.WriteBoolValue("start_anonymization", StartAnonymization);
        }
    }
}
#pragma warning restore CS0618
