// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BranchStorage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Always `true` in 200 responses. Present for forward compatibility: afuture version may add intermediate states; callers should treat `true`as \&quot;storage is usable for this branch right now.\&quot;&quot;</summary>
        public bool? Enabled { get; set; }
        /// <summary>&quot;Whether the S3 client must use path-style addressing(bucket-in-path rather than virtual-hosted subdomain).Always true: the wildcard TLS cert covers one level of subdomain(*.storage.&lt;suffix&gt;), so the branch ID occupies that label and thebucket name must travel in the request path, not as a furthersubdomain. Callers must set the S3 SDK&apos;s ForcePathStyle (orequivalent) to true.&quot;</summary>
        public bool? ForcePathStyle { get; set; }
        /// <summary>&quot;The AWS region for this branch&apos;s storage. The platform normalizesthe us-east-1 convention server-side: a non-empty region string isalways returned in 200 responses (e.g. `\&quot;us-east-1\&quot;` for the S3default region).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The S3-compatible endpoint URL for this branch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? S3Endpoint { get; set; }
#nullable restore
#else
        public string S3Endpoint { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.BranchStorage"/> and sets the default values.
        /// </summary>
        public BranchStorage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BranchStorage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.BranchStorage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.BranchStorage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "force_path_style", n => { ForcePathStyle = n.GetBoolValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "s3_endpoint", n => { S3Endpoint = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("force_path_style", ForcePathStyle);
            writer.WriteStringValue("region", Region);
            writer.WriteStringValue("s3_endpoint", S3Endpoint);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
