// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BranchSchemaJSON_tables : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The columns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_columns>? Columns { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_columns> Columns { get; set; }
#endif
        /// <summary>The constraints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_constraints>? Constraints { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_constraints> Constraints { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The schema property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Schema { get; set; }
#nullable restore
#else
        public string Schema { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables"/> and sets the default values.
        /// </summary>
        public BranchSchemaJSON_tables()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "columns", n => { Columns = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_columns>(global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_columns.CreateFromDiscriminatorValue)?.AsList(); } },
                { "constraints", n => { Constraints = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_constraints>(global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_constraints.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "schema", n => { Schema = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_columns>("columns", Columns);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BranchSchemaJSON_tables_constraints>("constraints", Constraints);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("schema", Schema);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
