// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>How the branch was deleted: &apos;user&apos; for manual deletion, &apos;ttl&apos; for TTL expiration</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BranchRecoveryInfo_deletion_method
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "ttl")]
        #pragma warning disable CS1591
        Ttl,
        #pragma warning restore CS1591
    }
}
