// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>Access level for the bucket. Defaults to `private`. Set to `public_read`to allow anonymous `GetObject`/`HeadObject` on objects in this bucket.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BucketCreateRequestAccessLevel
    {
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        PrivateValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "public_read")]
        #pragma warning disable CS1591
        PublicRead,
        #pragma warning restore CS1591
    }
}
