// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BucketObjectsListResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Common prefixes (folder names) collapsed under the requested`delimiter`. Empty when no `delimiter` was supplied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Folders { get; set; }
#nullable restore
#else
        public List<string> Folders { get; set; }
#endif
        /// <summary>True when more results exist beyond this page.</summary>
        public bool? IsTruncated { get; set; }
        /// <summary>Pagination cursor to pass as `cursor` on the next request. Emptywhen the listing is not truncated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>Objects whose keys did not collapse into a folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.BucketObject>? Objects { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.BucketObject> Objects { get; set; }
#endif
        /// <summary>The prefix that was applied to this listing (echoed back).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prefix { get; set; }
#nullable restore
#else
        public string Prefix { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.BucketObjectsListResponse"/> and sets the default values.
        /// </summary>
        public BucketObjectsListResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.BucketObjectsListResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.BucketObjectsListResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.BucketObjectsListResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "folders", n => { Folders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "is_truncated", n => { IsTruncated = n.GetBoolValue(); } },
                { "next_cursor", n => { NextCursor = n.GetStringValue(); } },
                { "objects", n => { Objects = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BucketObject>(global::Soenneker.Neon.OpenApiClient.Models.BucketObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "prefix", n => { Prefix = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("folders", Folders);
            writer.WriteBoolValue("is_truncated", IsTruncated);
            writer.WriteStringValue("next_cursor", NextCursor);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.BucketObject>("objects", Objects);
            writer.WriteStringValue("prefix", Prefix);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
