// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConsumptionHistoryGranularity
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "hourly")]
        #pragma warning disable CS1591
        Hourly,
        #pragma warning restore CS1591
        [EnumMember(Value = "daily")]
        #pragma warning disable CS1591
        Daily,
        #pragma warning restore CS1591
        [EnumMember(Value = "monthly")]
        #pragma warning disable CS1591
        Monthly,
        #pragma warning restore CS1591
    }
}
