// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>A single capability you may request when issuing a credential. Acredential is granted a set of these; it may only perform actionsexplicitly listed in its scopes.This is the *requestable* set. Responses describing an existingcredential use `GrantedCredentialScope`, which is deliberately wider:a credential may have been granted a scope that this endpoint does notoffer, and a response must be able to report it.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CredentialScope
    {
        [EnumMember(Value = "storage:read")]
        #pragma warning disable CS1591
        StorageColonRead,
        #pragma warning restore CS1591
        [EnumMember(Value = "storage:write")]
        #pragma warning disable CS1591
        StorageColonWrite,
        #pragma warning restore CS1591
        [EnumMember(Value = "ai_gateway:invoke")]
        #pragma warning disable CS1591
        AiGatewayColonInvoke,
        #pragma warning restore CS1591
        [EnumMember(Value = "functions:invoke")]
        #pragma warning disable CS1591
        FunctionsColonInvoke,
        #pragma warning restore CS1591
    }
}
