// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>
    /// Create Neon Data API
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataAPICreateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Grant all permissions to the tables in the public schema to authenticated users</summary>
        public bool? AddDefaultGrants { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authentication provider to use for the Neon Data API</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.DataAPICreateRequest_auth_provider? AuthProvider { get; set; }
        /// <summary>The URL that lists the JWKS</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JwksUrl { get; set; }
#nullable restore
#else
        public string JwksUrl { get; set; }
#endif
        /// <summary>WARNING - using this setting will only reject tokens with adifferent audience claim. Tokens without audience claim will stillbe accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JwtAudience { get; set; }
#nullable restore
#else
        public string JwtAudience { get; set; }
#endif
        /// <summary>The name of the authentication provider (e.g., Clerk, Stytch, Auth0)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderName { get; set; }
#nullable restore
#else
        public string ProviderName { get; set; }
#endif
        /// <summary>Configuration settings for the Neon Data API</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings Settings { get; set; }
#endif
        /// <summary>Skip creating the auth schema and RLS functions</summary>
        public bool? SkipAuthSchema { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.DataAPICreateRequest"/> and sets the default values.
        /// </summary>
        public DataAPICreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.DataAPICreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.DataAPICreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.DataAPICreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_default_grants", n => { AddDefaultGrants = n.GetBoolValue(); } },
                { "auth_provider", n => { AuthProvider = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.DataAPICreateRequest_auth_provider>(); } },
                { "jwks_url", n => { JwksUrl = n.GetStringValue(); } },
                { "jwt_audience", n => { JwtAudience = n.GetStringValue(); } },
                { "provider_name", n => { ProviderName = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings>(global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings.CreateFromDiscriminatorValue); } },
                { "skip_auth_schema", n => { SkipAuthSchema = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("add_default_grants", AddDefaultGrants);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.DataAPICreateRequest_auth_provider>("auth_provider", AuthProvider);
            writer.WriteStringValue("jwks_url", JwksUrl);
            writer.WriteStringValue("jwt_audience", JwtAudience);
            writer.WriteStringValue("provider_name", ProviderName);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings>("settings", Settings);
            writer.WriteBoolValue("skip_auth_schema", SkipAuthSchema);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
