// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>
    /// Configuration settings for the Neon Data API
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataAPISettings : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enable aggregates feature</summary>
        public bool? DbAggregatesEnabled { get; set; }
        /// <summary>Database role to use for anonymous requests</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DbAnonRole { get; set; }
#nullable restore
#else
        public string DbAnonRole { get; set; }
#endif
        /// <summary>Extra schemas to add to the search path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DbExtraSearchPath { get; set; }
#nullable restore
#else
        public string DbExtraSearchPath { get; set; }
#endif
        /// <summary>Maximum number of rows that can be returned in a single request</summary>
        public int? DbMaxRows { get; set; }
        /// <summary>List of schemas to expose via the API. Default: [&quot;public&quot;]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DbSchemas { get; set; }
#nullable restore
#else
        public List<string> DbSchemas { get; set; }
#endif
        /// <summary>Maximum lifetime for JWT cache in seconds</summary>
        public int? JwtCacheMaxLifetime { get; set; }
        /// <summary>JWT claim key to use for role extraction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JwtRoleClaimKey { get; set; }
#nullable restore
#else
        public string JwtRoleClaimKey { get; set; }
#endif
        /// <summary>OpenAPI specification mode (ignore-privileges, disabled)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpenapiMode { get; set; }
#nullable restore
#else
        public string OpenapiMode { get; set; }
#endif
        /// <summary>CORS allowed origins</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerCorsAllowedOrigins { get; set; }
#nullable restore
#else
        public string ServerCorsAllowedOrigins { get; set; }
#endif
        /// <summary>Enable server timing headers</summary>
        public bool? ServerTimingEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings"/> and sets the default values.
        /// </summary>
        public DataAPISettings()
        {
            AdditionalData = new Dictionary<string, object>();
            DbAnonRole = "anonymous";
            JwtRoleClaimKey = ".role";
            OpenapiMode = "disabled";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.DataAPISettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "db_aggregates_enabled", n => { DbAggregatesEnabled = n.GetBoolValue(); } },
                { "db_anon_role", n => { DbAnonRole = n.GetStringValue(); } },
                { "db_extra_search_path", n => { DbExtraSearchPath = n.GetStringValue(); } },
                { "db_max_rows", n => { DbMaxRows = n.GetIntValue(); } },
                { "db_schemas", n => { DbSchemas = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "jwt_cache_max_lifetime", n => { JwtCacheMaxLifetime = n.GetIntValue(); } },
                { "jwt_role_claim_key", n => { JwtRoleClaimKey = n.GetStringValue(); } },
                { "openapi_mode", n => { OpenapiMode = n.GetStringValue(); } },
                { "server_cors_allowed_origins", n => { ServerCorsAllowedOrigins = n.GetStringValue(); } },
                { "server_timing_enabled", n => { ServerTimingEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("db_aggregates_enabled", DbAggregatesEnabled);
            writer.WriteStringValue("db_anon_role", DbAnonRole);
            writer.WriteStringValue("db_extra_search_path", DbExtraSearchPath);
            writer.WriteIntValue("db_max_rows", DbMaxRows);
            writer.WriteCollectionOfPrimitiveValues<string>("db_schemas", DbSchemas);
            writer.WriteIntValue("jwt_cache_max_lifetime", JwtCacheMaxLifetime);
            writer.WriteStringValue("jwt_role_claim_key", JwtRoleClaimKey);
            writer.WriteStringValue("openapi_mode", OpenapiMode);
            writer.WriteStringValue("server_cors_allowed_origins", ServerCorsAllowedOrigins);
            writer.WriteBoolValue("server_timing_enabled", ServerTimingEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
