// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EndpointUpdateRequest_endpoint : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autoscaling_limit_max_cu property</summary>
        public double? AutoscalingLimitMaxCu { get; set; }
        /// <summary>The autoscaling_limit_min_cu property</summary>
        public double? AutoscalingLimitMinCu { get; set; }
        /// <summary>DEPRECATED: This field will be removed in a future release.The destination branch ID. The destination branch must not have an existing read-write endpoint.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BranchId { get; set; }
#nullable restore
#else
        public string BranchId { get; set; }
#endif
        /// <summary>Whether to restrict connections to the compute endpoint.Enabling this option schedules a suspend compute operation.A disabled compute endpoint cannot be enabled by a connection orconsole action. However, the compute endpoint is periodicallyenabled by check_availability operations.</summary>
        public bool? Disabled { get; set; }
        /// <summary>Optional name of the compute endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>NOT YET IMPLEMENTED. Whether to permit passwordless access to the compute endpoint.</summary>
        public bool? PasswordlessAccess { get; set; }
        /// <summary>Whether to enable connection pooling for the compute endpoint</summary>
        [Obsolete("")]
        public bool? PoolerEnabled { get; set; }
        /// <summary>DEPRECATED. The connection pooler mode. Neon supports PgBouncer in `transaction` mode only. This schema is deprecated and will be removed after 2026-06-20.</summary>
        [Obsolete("")]
        public global::Soenneker.Neon.OpenApiClient.Models.EndpointPoolerMode? PoolerMode { get; set; }
        /// <summary>The Neon compute provisioner.Specify the `k8s-neonvm` provisioner to create a compute endpoint that supports Autoscaling.Provisioner can be one of the following values:* k8s-pod* k8s-neonvm* serverless-platformClients must expect, that any string value that is not documented in the description above should be treated as a error. UNKNOWN value if safe to treat as an error too.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provisioner { get; set; }
#nullable restore
#else
        public string Provisioner { get; set; }
#endif
        /// <summary>A collection of settings for a compute endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData Settings { get; set; }
#endif
        /// <summary>Duration of inactivity in seconds after which the compute endpoint isautomatically suspended. The value `0` means use the default value.The value `-1` means never suspend. The default value is `300` seconds (5 minutes).The minimum value is `60` seconds (1 minute).The maximum value is `604800` seconds (1 week). For more information, see[Scale to zero configuration](https://neon.tech/docs/manage/endpoints#scale-to-zero-configuration).</summary>
        public long? SuspendTimeoutSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.EndpointUpdateRequest_endpoint"/> and sets the default values.
        /// </summary>
        public EndpointUpdateRequest_endpoint()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.EndpointUpdateRequest_endpoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.EndpointUpdateRequest_endpoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.EndpointUpdateRequest_endpoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoscaling_limit_max_cu", n => { AutoscalingLimitMaxCu = n.GetDoubleValue(); } },
                { "autoscaling_limit_min_cu", n => { AutoscalingLimitMinCu = n.GetDoubleValue(); } },
                { "branch_id", n => { BranchId = n.GetStringValue(); } },
                { "disabled", n => { Disabled = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "passwordless_access", n => { PasswordlessAccess = n.GetBoolValue(); } },
                { "pooler_enabled", n => { PoolerEnabled = n.GetBoolValue(); } },
                { "pooler_mode", n => { PoolerMode = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.EndpointPoolerMode>(); } },
                { "provisioner", n => { Provisioner = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData>(global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData.CreateFromDiscriminatorValue); } },
                { "suspend_timeout_seconds", n => { SuspendTimeoutSeconds = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("autoscaling_limit_max_cu", AutoscalingLimitMaxCu);
            writer.WriteDoubleValue("autoscaling_limit_min_cu", AutoscalingLimitMinCu);
            writer.WriteStringValue("branch_id", BranchId);
            writer.WriteBoolValue("disabled", Disabled);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("passwordless_access", PasswordlessAccess);
            writer.WriteBoolValue("pooler_enabled", PoolerEnabled);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.EndpointPoolerMode>("pooler_mode", PoolerMode);
            writer.WriteStringValue("provisioner", Provisioner);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData>("settings", Settings);
            writer.WriteLongValue("suspend_timeout_seconds", SuspendTimeoutSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
