// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>The state of the compute endpoint</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EndpointState
    {
        [EnumMember(Value = "init")]
        #pragma warning disable CS1591
        Init,
        #pragma warning restore CS1591
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "idle")]
        #pragma warning disable CS1591
        Idle,
        #pragma warning restore CS1591
    }
}
