// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>The compute endpoint type. Either `read_write` or `read_only`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EndpointType
    {
        [EnumMember(Value = "read_only")]
        #pragma warning disable CS1591
        ReadOnlyValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "read_write")]
        #pragma warning disable CS1591
        ReadWrite,
        #pragma warning restore CS1591
    }
}
