// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>
    /// A collection of settings for a compute endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EndpointSettingsData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>DEPRECATED. A raw representation of PgBouncer settings. This schema is deprecated and will be removed after 2026-06-20.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.PgbouncerSettingsData? PgbouncerSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.PgbouncerSettingsData PgbouncerSettings { get; set; }
#endif
        /// <summary>A raw representation of Postgres settings</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.PgSettingsData? PgSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.PgSettingsData PgSettings { get; set; }
#endif
        /// <summary>The shared libraries to preload into the project&apos;s compute instances.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.PreloadLibraries? PreloadLibraries { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.PreloadLibraries PreloadLibraries { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData"/> and sets the default values.
        /// </summary>
        public EndpointSettingsData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.EndpointSettingsData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pg_settings", n => { PgSettings = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PgSettingsData>(global::Soenneker.Neon.OpenApiClient.Models.PgSettingsData.CreateFromDiscriminatorValue); } },
                { "pgbouncer_settings", n => { PgbouncerSettings = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PgbouncerSettingsData>(global::Soenneker.Neon.OpenApiClient.Models.PgbouncerSettingsData.CreateFromDiscriminatorValue); } },
                { "preload_libraries", n => { PreloadLibraries = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PreloadLibraries>(global::Soenneker.Neon.OpenApiClient.Models.PreloadLibraries.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PgbouncerSettingsData>("pgbouncer_settings", PgbouncerSettings);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PgSettingsData>("pg_settings", PgSettings);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.PreloadLibraries>("preload_libraries", PreloadLibraries);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
