// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FunctionDeployRequestRuntime
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "nodejs24")]
        #pragma warning disable CS1591
        Nodejs24,
        #pragma warning restore CS1591
    }
}
