// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetConsumptionHistoryPerBranchV2200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The branches property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Neon.OpenApiClient.Models.ConsumptionHistoryPerBranchV2>? Branches { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Neon.OpenApiClient.Models.ConsumptionHistoryPerBranchV2> Branches { get; set; }
#endif
        /// <summary>Cursor based pagination is used. The user must pass the cursor as is to the backend.For more information about cursor based pagination, seehttps://learn.microsoft.com/en-us/ef/core/querying/pagination#keyset-pagination</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.Pagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.Pagination Pagination { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.GetConsumptionHistoryPerBranchV2200"/> and sets the default values.
        /// </summary>
        public GetConsumptionHistoryPerBranchV2200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.GetConsumptionHistoryPerBranchV2200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.GetConsumptionHistoryPerBranchV2200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.GetConsumptionHistoryPerBranchV2200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branches", n => { Branches = n.GetCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.ConsumptionHistoryPerBranchV2>(global::Soenneker.Neon.OpenApiClient.Models.ConsumptionHistoryPerBranchV2.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.Pagination>(global::Soenneker.Neon.OpenApiClient.Models.Pagination.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Neon.OpenApiClient.Models.ConsumptionHistoryPerBranchV2>("branches", Branches);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.Pagination>("pagination", Pagination);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
