// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetProjectAdvisorSecurityIssuesMinSeverityParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "INFO")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "WARN")]
        #pragma warning disable CS1591
        Warn,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
