// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>Identity provider id from keycloak</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IdentityProviderId
    {
        [EnumMember(Value = "github")]
        #pragma warning disable CS1591
        Github,
        #pragma warning restore CS1591
        [EnumMember(Value = "google")]
        #pragma warning disable CS1591
        Google,
        #pragma warning restore CS1591
        [EnumMember(Value = "hasura")]
        #pragma warning disable CS1591
        Hasura,
        #pragma warning restore CS1591
        [EnumMember(Value = "microsoft")]
        #pragma warning disable CS1591
        Microsoft,
        #pragma warning restore CS1591
        [EnumMember(Value = "microsoftv2")]
        #pragma warning disable CS1591
        Microsoftv2,
        #pragma warning restore CS1591
        [EnumMember(Value = "vercelmp")]
        #pragma warning disable CS1591
        Vercelmp,
        #pragma warning restore CS1591
        [EnumMember(Value = "keycloak")]
        #pragma warning disable CS1591
        Keycloak,
        #pragma warning restore CS1591
    }
}
