// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListProjectBranchesSortByParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
    }
}
