// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>The email verification method to use.- `link`: Sends a verification link via email- `otp`: Sends a one-time password (OTP) via email</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NeonAuthEmailVerificationMethod
    {
        [EnumMember(Value = "link")]
        #pragma warning disable CS1591
        Link,
        #pragma warning restore CS1591
        [EnumMember(Value = "otp")]
        #pragma warning disable CS1591
        Otp,
        #pragma warning restore CS1591
    }
}
