// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NeonAuthEmailAndPasswordConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether users are automatically signed in after verifying their email</summary>
        public bool? AutoSignInAfterVerification { get; set; }
        /// <summary>Whether to disable new user sign ups</summary>
        public bool? DisableSignUp { get; set; }
        /// <summary>The email verification method to use.- `link`: Sends a verification link via email- `otp`: Sends a one-time password (OTP) via email</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.NeonAuthEmailVerificationMethod? EmailVerificationMethod { get; set; }
        /// <summary>Whether email and password authentication is enabled</summary>
        public bool? Enabled { get; set; }
        /// <summary>Whether email verification is required before users can sign in</summary>
        public bool? RequireEmailVerification { get; set; }
        /// <summary>Whether to send a verification email when users sign in</summary>
        public bool? SendVerificationEmailOnSignIn { get; set; }
        /// <summary>Whether to send a verification email when users sign up</summary>
        public bool? SendVerificationEmailOnSignUp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.NeonAuthEmailAndPasswordConfig"/> and sets the default values.
        /// </summary>
        public NeonAuthEmailAndPasswordConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.NeonAuthEmailAndPasswordConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.NeonAuthEmailAndPasswordConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.NeonAuthEmailAndPasswordConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_sign_in_after_verification", n => { AutoSignInAfterVerification = n.GetBoolValue(); } },
                { "disable_sign_up", n => { DisableSignUp = n.GetBoolValue(); } },
                { "email_verification_method", n => { EmailVerificationMethod = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthEmailVerificationMethod>(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "require_email_verification", n => { RequireEmailVerification = n.GetBoolValue(); } },
                { "send_verification_email_on_sign_in", n => { SendVerificationEmailOnSignIn = n.GetBoolValue(); } },
                { "send_verification_email_on_sign_up", n => { SendVerificationEmailOnSignUp = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto_sign_in_after_verification", AutoSignInAfterVerification);
            writer.WriteBoolValue("disable_sign_up", DisableSignUp);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.NeonAuthEmailVerificationMethod>("email_verification_method", EmailVerificationMethod);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("require_email_verification", RequireEmailVerification);
            writer.WriteBoolValue("send_verification_email_on_sign_in", SendVerificationEmailOnSignIn);
            writer.WriteBoolValue("send_verification_email_on_sign_up", SendVerificationEmailOnSignUp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
