// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NeonAuthOauthProviderType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "standard")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
        [EnumMember(Value = "shared")]
        #pragma warning disable CS1591
        Shared,
        #pragma warning restore CS1591
    }
}
