// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>The action performed by the operation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OperationAction
    {
        [EnumMember(Value = "create_compute")]
        #pragma warning disable CS1591
        Create_compute,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_timeline")]
        #pragma warning disable CS1591
        Create_timeline,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_compute")]
        #pragma warning disable CS1591
        Start_compute,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspend_compute")]
        #pragma warning disable CS1591
        Suspend_compute,
        #pragma warning restore CS1591
        [EnumMember(Value = "apply_config")]
        #pragma warning disable CS1591
        Apply_config,
        #pragma warning restore CS1591
        [EnumMember(Value = "check_availability")]
        #pragma warning disable CS1591
        Check_availability,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete_timeline")]
        #pragma warning disable CS1591
        Delete_timeline,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_branch")]
        #pragma warning disable CS1591
        Create_branch,
        #pragma warning restore CS1591
        [EnumMember(Value = "import_data")]
        #pragma warning disable CS1591
        Import_data,
        #pragma warning restore CS1591
        [EnumMember(Value = "tenant_ignore")]
        #pragma warning disable CS1591
        Tenant_ignore,
        #pragma warning restore CS1591
        [EnumMember(Value = "tenant_attach")]
        #pragma warning disable CS1591
        Tenant_attach,
        #pragma warning restore CS1591
        [EnumMember(Value = "tenant_detach")]
        #pragma warning disable CS1591
        Tenant_detach,
        #pragma warning restore CS1591
        [EnumMember(Value = "tenant_reattach")]
        #pragma warning disable CS1591
        Tenant_reattach,
        #pragma warning restore CS1591
        [EnumMember(Value = "replace_safekeeper")]
        #pragma warning disable CS1591
        Replace_safekeeper,
        #pragma warning restore CS1591
        [EnumMember(Value = "disable_maintenance")]
        #pragma warning disable CS1591
        Disable_maintenance,
        #pragma warning restore CS1591
        [EnumMember(Value = "apply_storage_config")]
        #pragma warning disable CS1591
        Apply_storage_config,
        #pragma warning restore CS1591
        [EnumMember(Value = "prepare_secondary_pageserver")]
        #pragma warning disable CS1591
        Prepare_secondary_pageserver,
        #pragma warning restore CS1591
        [EnumMember(Value = "switch_pageserver")]
        #pragma warning disable CS1591
        Switch_pageserver,
        #pragma warning restore CS1591
        [EnumMember(Value = "detach_parent_branch")]
        #pragma warning disable CS1591
        Detach_parent_branch,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeline_archive")]
        #pragma warning disable CS1591
        Timeline_archive,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeline_unarchive")]
        #pragma warning disable CS1591
        Timeline_unarchive,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_reserved_compute")]
        #pragma warning disable CS1591
        Start_reserved_compute,
        #pragma warning restore CS1591
        [EnumMember(Value = "sync_dbs_and_roles_from_compute")]
        #pragma warning disable CS1591
        Sync_dbs_and_roles_from_compute,
        #pragma warning restore CS1591
        [EnumMember(Value = "apply_schema_from_branch")]
        #pragma warning disable CS1591
        Apply_schema_from_branch,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeline_mark_invisible")]
        #pragma warning disable CS1591
        Timeline_mark_invisible,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeline_update_protected_config")]
        #pragma warning disable CS1591
        Timeline_update_protected_config,
        #pragma warning restore CS1591
        [EnumMember(Value = "prewarm_replica")]
        #pragma warning disable CS1591
        Prewarm_replica,
        #pragma warning restore CS1591
        [EnumMember(Value = "promote_replica")]
        #pragma warning disable CS1591
        Promote_replica,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_storage_non_dirty")]
        #pragma warning disable CS1591
        Set_storage_non_dirty,
        #pragma warning restore CS1591
        [EnumMember(Value = "swap_binding_id")]
        #pragma warning disable CS1591
        Swap_binding_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "finalize_migration")]
        #pragma warning disable CS1591
        Finalize_migration,
        #pragma warning restore CS1591
        [EnumMember(Value = "mark_migration_prepared")]
        #pragma warning disable CS1591
        Mark_migration_prepared,
        #pragma warning restore CS1591
    }
}
