// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>
    /// Options for the presigned URL. The `operation` selects upload (`PUT`)or download (`GET`); the remaining fields are optional.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PresignRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;The `Content-Type` to bind into the signed request. Only meaningfulfor `upload`: when set, the caller MUST send the same `Content-Type`header on the `PUT`, and the value is echoed back in the response`headers`. Ignored for `download`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>How long the presigned URL stays valid, in seconds. Defaults to 900(15 minutes); capped at 604800 (7 days).</summary>
        public long? ExpiresInSeconds { get; set; }
        /// <summary>The transfer direction. `upload` returns a presigned `PUT` URL;`download` returns a presigned `GET` URL.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.PresignRequestOperation? Operation { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.PresignRequest"/> and sets the default values.
        /// </summary>
        public PresignRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            ExpiresInSeconds = 900;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.PresignRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.PresignRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.PresignRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content_type", n => { ContentType = n.GetStringValue(); } },
                { "expires_in_seconds", n => { ExpiresInSeconds = n.GetLongValue(); } },
                { "operation", n => { Operation = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.PresignRequestOperation>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("content_type", ContentType);
            writer.WriteLongValue("expires_in_seconds", ExpiresInSeconds);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.PresignRequestOperation>("operation", Operation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
