// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectBranchLogRecord : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Customer-defined OpenTelemetry log and resource attributes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecordAttributesProperty? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecordAttributesProperty Attributes { get; set; }
#endif
        /// <summary>The Neon identifier of the service instance that emitted the record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityId { get; set; }
#nullable restore
#else
        public string EntityId { get; set; }
#endif
        /// <summary>The OpenTelemetry log body rendered as text. A body that is already astring is returned verbatim. Any other OpenTelemetry `AnyValue` body— notably the structured key/value body that `storage` records alwayscarry — is rendered as compact JSON with its keys sortedalphabetically, for example`{&quot;bytes&quot;:1024,&quot;operation&quot;:&quot;GET&quot;,&quot;object_key&quot;:&quot;a/b.png&quot;}`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The OpenTelemetry instrumentation scope name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScopeName { get; set; }
#nullable restore
#else
        public string ScopeName { get; set; }
#endif
        /// <summary>The OpenTelemetry `service.name` resource attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceName { get; set; }
#nullable restore
#else
        public string ServiceName { get; set; }
#endif
        /// <summary>The numeric OpenTelemetry severity.</summary>
        public int? SeverityNumber { get; set; }
        /// <summary>The original OpenTelemetry severity text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeverityText { get; set; }
#nullable restore
#else
        public string SeverityText { get; set; }
#endif
        /// <summary>The Neon service that emitted the log record.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogSource? Source { get; set; }
        /// <summary>The OpenTelemetry span ID, when the record belongs to a span.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpanId { get; set; }
#nullable restore
#else
        public string SpanId { get; set; }
#endif
        /// <summary>The OpenTelemetry record timestamp in UTC.</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>The OpenTelemetry trace ID, when the record belongs to a trace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TraceId { get; set; }
#nullable restore
#else
        public string TraceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecord"/> and sets the default values.
        /// </summary>
        public ProjectBranchLogRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecordAttributesProperty>(global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecordAttributesProperty.CreateFromDiscriminatorValue); } },
                { "entity_id", n => { EntityId = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "scope_name", n => { ScopeName = n.GetStringValue(); } },
                { "service_name", n => { ServiceName = n.GetStringValue(); } },
                { "severity_number", n => { SeverityNumber = n.GetIntValue(); } },
                { "severity_text", n => { SeverityText = n.GetStringValue(); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogSource>(); } },
                { "span_id", n => { SpanId = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
                { "trace_id", n => { TraceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogRecordAttributesProperty>("attributes", Attributes);
            writer.WriteStringValue("entity_id", EntityId);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("scope_name", ScopeName);
            writer.WriteStringValue("service_name", ServiceName);
            writer.WriteIntValue("severity_number", SeverityNumber);
            writer.WriteStringValue("severity_text", SeverityText);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectBranchLogSource>("source", Source);
            writer.WriteStringValue("span_id", SpanId);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteStringValue("trace_id", TraceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
