// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Project : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Seconds. Control plane observed endpoints of this project being active this amount of wall-clock time.The value has some lag.The value is reset at the beginning of each billing period.</summary>
        public long? ActiveTimeSeconds { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The logical size limit for a branch. The value is in MiB.</summary>
        public long? BranchLogicalSizeLimit { get; set; }
        /// <summary>The logical size limit for a branch. The value is in B.</summary>
        public long? BranchLogicalSizeLimitBytes { get; set; }
        /// <summary>The most recent time when any endpoint of this project was active.Omitted when observed no activity for endpoints of this project.</summary>
        public DateTimeOffset? ComputeLastActiveAt { get; set; }
        /// <summary>Seconds. The number of CPU seconds used by the project&apos;s compute endpoints, including compute endpoints that have been deleted.The value has some lag. The value is reset at the beginning of each billing period.Examples:1. An endpoint that uses 1 CPU for 1 second is equal to `compute_time=1`.2. An endpoint that uses 2 CPUs simultaneously for 1 second is equal to `compute_time=2`.</summary>
        public long? ComputeTimeSeconds { get; set; }
        /// <summary>A date-time indicating when Neon Cloud plans to stop measuring consumption for current consumption period.</summary>
        public DateTimeOffset? ConsumptionPeriodEnd { get; set; }
        /// <summary>A date-time indicating when Neon Cloud started measuring consumption for current consumption period.</summary>
        public DateTimeOffset? ConsumptionPeriodStart { get; set; }
        /// <summary>DEPRECATED, use compute_time instead.</summary>
        [Obsolete("")]
        public long? CpuUsedSec { get; set; }
        /// <summary>A timestamp indicating when the project was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The project creation source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreationSource { get; set; }
#nullable restore
#else
        public string CreationSource { get; set; }
#endif
        /// <summary>Bytes-Hour. Project consumed that much storage hourly during the billing period. The value has some lag.The value is reset at the beginning of each billing period.</summary>
        public long? DataStorageBytesHour { get; set; }
        /// <summary>Bytes. Egress traffic from the Neon cloud to the client for given project over the billing period.Includes deleted endpoints. The value has some lag. The value is reset at the beginning of each billing period.</summary>
        public long? DataTransferBytes { get; set; }
        /// <summary>A collection of settings for a Neon endpoint</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.DefaultEndpointSettings? DefaultEndpointSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.DefaultEndpointSettings DefaultEndpointSettings { get; set; }
#endif
        /// <summary>A timestamp indicating when HIPAA was enabled for this project</summary>
        public DateTimeOffset? HipaaEnabledAt { get; set; }
        /// <summary>The number of seconds to retain the shared history for all branches in this project.</summary>
        public int? HistoryRetentionSeconds { get; set; }
        /// <summary>The project ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>A timestamp indicating when project update begins. If set, computes might experience a brief restart around this time.</summary>
        public DateTimeOffset? MaintenanceScheduledFor { get; set; }
        /// <summary>A timestamp indicating when project maintenance begins. If set, the project is placed into maintenance mode at this time.</summary>
        public DateTimeOffset? MaintenanceStartsAt { get; set; }
        /// <summary>The project name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The org_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectOwnerData? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectOwnerData Owner { get; set; }
#endif
        /// <summary>The owner_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The major Postgres version number. Currently supported versions are `14`, `15`, `16`, `17`, and `18`.</summary>
        public int? PgVersion { get; set; }
        /// <summary>The cloud platform identifier. Currently, only AWS is supported, for which the identifier is `aws`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlatformId { get; set; }
#nullable restore
#else
        public string PlatformId { get; set; }
#endif
        /// <summary>The Neon compute provisioner.Specify the `k8s-neonvm` provisioner to create a compute endpoint that supports Autoscaling.Provisioner can be one of the following values:* k8s-pod* k8s-neonvm* serverless-platformClients must expect, that any string value that is not documented in the description above should be treated as a error. UNKNOWN value if safe to treat as an error too.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provisioner { get; set; }
#nullable restore
#else
        public string Provisioner { get; set; }
#endif
        /// <summary>The proxy host for the project. This value combines the `region_id`, the `platform_id`, and the Neon domain (`neon.tech`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProxyHost { get; set; }
#nullable restore
#else
        public string ProxyHost { get; set; }
#endif
        /// <summary>DEPRECATED. Use `consumption_period_end` from the getProject endpoint instead.A timestamp indicating when the project quota resets.</summary>
        [Obsolete("")]
        public DateTimeOffset? QuotaResetAt { get; set; }
        /// <summary>The region identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegionId { get; set; }
#nullable restore
#else
        public string RegionId { get; set; }
#endif
        /// <summary>The settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectSettingsData? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectSettingsData Settings { get; set; }
#endif
        /// <summary>Whether or not passwords are stored for roles in the Neon project. Storing passwords facilitates access to Neon features that require authorization.</summary>
        public bool? StorePasswords { get; set; }
        /// <summary>The current space occupied by the project in storage, in bytes. Synthetic storage size combines the logical data size and Write-Ahead Log (WAL) size for all branches in a project.</summary>
        public long? SyntheticStorageSize { get; set; }
        /// <summary>A timestamp indicating when the project was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Bytes. Amount of WAL that travelled through storage for given project across all branches.The value has some lag. The value is reset at the beginning of each billing period.</summary>
        public long? WrittenDataBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.Project"/> and sets the default values.
        /// </summary>
        public Project()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.Project"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.Project CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.Project();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_time_seconds", n => { ActiveTimeSeconds = n.GetLongValue(); } },
                { "branch_logical_size_limit", n => { BranchLogicalSizeLimit = n.GetLongValue(); } },
                { "branch_logical_size_limit_bytes", n => { BranchLogicalSizeLimitBytes = n.GetLongValue(); } },
                { "compute_last_active_at", n => { ComputeLastActiveAt = n.GetDateTimeOffsetValue(); } },
                { "compute_time_seconds", n => { ComputeTimeSeconds = n.GetLongValue(); } },
                { "consumption_period_end", n => { ConsumptionPeriodEnd = n.GetDateTimeOffsetValue(); } },
                { "consumption_period_start", n => { ConsumptionPeriodStart = n.GetDateTimeOffsetValue(); } },
                { "cpu_used_sec", n => { CpuUsedSec = n.GetLongValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creation_source", n => { CreationSource = n.GetStringValue(); } },
                { "data_storage_bytes_hour", n => { DataStorageBytesHour = n.GetLongValue(); } },
                { "data_transfer_bytes", n => { DataTransferBytes = n.GetLongValue(); } },
                { "default_endpoint_settings", n => { DefaultEndpointSettings = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.DefaultEndpointSettings>(global::Soenneker.Neon.OpenApiClient.Models.DefaultEndpointSettings.CreateFromDiscriminatorValue); } },
                { "hipaa_enabled_at", n => { HipaaEnabledAt = n.GetDateTimeOffsetValue(); } },
                { "history_retention_seconds", n => { HistoryRetentionSeconds = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "maintenance_scheduled_for", n => { MaintenanceScheduledFor = n.GetDateTimeOffsetValue(); } },
                { "maintenance_starts_at", n => { MaintenanceStartsAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "org_id", n => { OrgId = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectOwnerData>(global::Soenneker.Neon.OpenApiClient.Models.ProjectOwnerData.CreateFromDiscriminatorValue); } },
                { "owner_id", n => { OwnerId = n.GetStringValue(); } },
                { "pg_version", n => { PgVersion = n.GetIntValue(); } },
                { "platform_id", n => { PlatformId = n.GetStringValue(); } },
                { "provisioner", n => { Provisioner = n.GetStringValue(); } },
                { "proxy_host", n => { ProxyHost = n.GetStringValue(); } },
                { "quota_reset_at", n => { QuotaResetAt = n.GetDateTimeOffsetValue(); } },
                { "region_id", n => { RegionId = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectSettingsData>(global::Soenneker.Neon.OpenApiClient.Models.ProjectSettingsData.CreateFromDiscriminatorValue); } },
                { "store_passwords", n => { StorePasswords = n.GetBoolValue(); } },
                { "synthetic_storage_size", n => { SyntheticStorageSize = n.GetLongValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "written_data_bytes", n => { WrittenDataBytes = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("active_time_seconds", ActiveTimeSeconds);
            writer.WriteLongValue("branch_logical_size_limit", BranchLogicalSizeLimit);
            writer.WriteLongValue("branch_logical_size_limit_bytes", BranchLogicalSizeLimitBytes);
            writer.WriteDateTimeOffsetValue("compute_last_active_at", ComputeLastActiveAt);
            writer.WriteLongValue("compute_time_seconds", ComputeTimeSeconds);
            writer.WriteDateTimeOffsetValue("consumption_period_end", ConsumptionPeriodEnd);
            writer.WriteDateTimeOffsetValue("consumption_period_start", ConsumptionPeriodStart);
            writer.WriteLongValue("cpu_used_sec", CpuUsedSec);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("creation_source", CreationSource);
            writer.WriteLongValue("data_storage_bytes_hour", DataStorageBytesHour);
            writer.WriteLongValue("data_transfer_bytes", DataTransferBytes);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.DefaultEndpointSettings>("default_endpoint_settings", DefaultEndpointSettings);
            writer.WriteDateTimeOffsetValue("hipaa_enabled_at", HipaaEnabledAt);
            writer.WriteIntValue("history_retention_seconds", HistoryRetentionSeconds);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("maintenance_scheduled_for", MaintenanceScheduledFor);
            writer.WriteDateTimeOffsetValue("maintenance_starts_at", MaintenanceStartsAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("org_id", OrgId);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectOwnerData>("owner", Owner);
            writer.WriteStringValue("owner_id", OwnerId);
            writer.WriteIntValue("pg_version", PgVersion);
            writer.WriteStringValue("platform_id", PlatformId);
            writer.WriteStringValue("provisioner", Provisioner);
            writer.WriteStringValue("proxy_host", ProxyHost);
            writer.WriteDateTimeOffsetValue("quota_reset_at", QuotaResetAt);
            writer.WriteStringValue("region_id", RegionId);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectSettingsData>("settings", Settings);
            writer.WriteBoolValue("store_passwords", StorePasswords);
            writer.WriteLongValue("synthetic_storage_size", SyntheticStorageSize);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteLongValue("written_data_bytes", WrittenDataBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
