// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>Order matching records by timestamp. `desc`, the default, returnsthe newest records first.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectBranchLogsQueryRequestSortOrder
    {
        [EnumMember(Value = "asc")]
        #pragma warning disable CS1591
        Asc,
        #pragma warning restore CS1591
        [EnumMember(Value = "desc")]
        #pragma warning disable CS1591
        Desc,
        #pragma warning restore CS1591
    }
}
