// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>Per-project role. `viewer` maps to `VIEWER`, `editor` maps to `EDITOR`,and `admin` maps to `ADMIN`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectRole
    {
        [EnumMember(Value = "viewer")]
        #pragma warning disable CS1591
        Viewer,
        #pragma warning restore CS1591
        [EnumMember(Value = "editor")]
        #pragma warning disable CS1591
        Editor,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
    }
}
