// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>
    /// Per-project consumption quotas. If a quota is exceeded, all active computesare automatically suspended and cannot be started via API calls or incoming connections.The exception is `logical_size_bytes`, which is enforced per branch.If a branch exceeds its `logical_size_bytes` quota, computes can still be started,but write operations will fail—allowing data to be deleted to free up space.Computes on other branches are not affected.Setting `logical_size_bytes` overrides any lower value set by the `neon.max_cluster_size` Postgres setting.Quotas are enforced using per-project consumption metrics with the same names.These metrics reset at the start of each billing period. `logical_size_bytes`is also an exception—it reflects the total data stored in a branch and does not reset.A zero or empty quota value means “unlimited.”
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectQuota : IAdditionalDataHolder, IParsable
    {
        /// <summary>The total amount of wall-clock time allowed to be spent by the project&apos;s compute endpoints.</summary>
        public long? ActiveTimeSeconds { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The total amount of CPU seconds allowed to be spent by the project&apos;s compute endpoints.</summary>
        public long? ComputeTimeSeconds { get; set; }
        /// <summary>Total amount of data transferred from all of a project&apos;s branches using the proxy.</summary>
        public long? DataTransferBytes { get; set; }
        /// <summary>Limit on the logical size of every project&apos;s branch.If a branch exceeds its `logical_size_bytes` quota, computes can still be started,but write operations will fail—allowing data to be deleted to free up space.Computes on other branches are not affected.Setting `logical_size_bytes` overrides any lower value set by the `neon.max_cluster_size` Postgres setting.</summary>
        public long? LogicalSizeBytes { get; set; }
        /// <summary>Total amount of data written to all of a project&apos;s branches.</summary>
        public long? WrittenDataBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.ProjectQuota"/> and sets the default values.
        /// </summary>
        public ProjectQuota()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.ProjectQuota"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.ProjectQuota CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.ProjectQuota();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_time_seconds", n => { ActiveTimeSeconds = n.GetLongValue(); } },
                { "compute_time_seconds", n => { ComputeTimeSeconds = n.GetLongValue(); } },
                { "data_transfer_bytes", n => { DataTransferBytes = n.GetLongValue(); } },
                { "logical_size_bytes", n => { LogicalSizeBytes = n.GetLongValue(); } },
                { "written_data_bytes", n => { WrittenDataBytes = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("active_time_seconds", ActiveTimeSeconds);
            writer.WriteLongValue("compute_time_seconds", ComputeTimeSeconds);
            writer.WriteLongValue("data_transfer_bytes", DataTransferBytes);
            writer.WriteLongValue("logical_size_bytes", LogicalSizeBytes);
            writer.WriteLongValue("written_data_bytes", WrittenDataBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
