// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectMember : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The caller&apos;s effective permission for a project whenper-project permissions are enabled. `VIEWER` grants read access,`EDITOR` adds update access, and `ADMIN` grants full management.Omitted for personal projects, flag-off organizations, and non-usersubjects.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel? EffectiveProjectPermission { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The caller&apos;s effective permission for a project whenper-project permissions are enabled. `VIEWER` grants read access,`EDITOR` adds update access, and `ADMIN` grants full management.Omitted for personal projects, flag-off organizations, and non-usersubjects.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel? ExplicitProjectPermission { get; set; }
        /// <summary>How a member&apos;s project access is granted.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectMemberGrantSource? GrantSource { get; set; }
        /// <summary>The organization member ID.</summary>
        public Guid? MemberId { get; set; }
        /// <summary>The user&apos;s display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The caller&apos;s effective permission for a project whenper-project permissions are enabled. `VIEWER` grants read access,`EDITOR` adds update access, and `ADMIN` grants full management.Omitted for personal projects, flag-off organizations, and non-usersubjects.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel? OrgDefaultProjectPermission { get; set; }
        /// <summary>Organization-level role used by project member role management.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectMemberOrgRole? OrgRole { get; set; }
        /// <summary>Per-project role. `viewer` maps to `VIEWER`, `editor` maps to `EDITOR`,and `admin` maps to `ADMIN`.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ProjectRole? ProjectRole { get; set; }
        /// <summary>The user ID for the organization member.</summary>
        public Guid? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.ProjectMember"/> and sets the default values.
        /// </summary>
        public ProjectMember()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.ProjectMember"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.ProjectMember CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.ProjectMember();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "effective_project_permission", n => { EffectiveProjectPermission = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel>(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "explicit_project_permission", n => { ExplicitProjectPermission = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel>(); } },
                { "grant_source", n => { GrantSource = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectMemberGrantSource>(); } },
                { "member_id", n => { MemberId = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "org_default_project_permission", n => { OrgDefaultProjectPermission = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel>(); } },
                { "org_role", n => { OrgRole = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectMemberOrgRole>(); } },
                { "project_role", n => { ProjectRole = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectRole>(); } },
                { "user_id", n => { UserId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel>("effective_project_permission", EffectiveProjectPermission);
            writer.WriteStringValue("email", Email);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel>("explicit_project_permission", ExplicitProjectPermission);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectMemberGrantSource>("grant_source", GrantSource);
            writer.WriteGuidValue("member_id", MemberId);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectPermissionLevel>("org_default_project_permission", OrgDefaultProjectPermission);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectMemberOrgRole>("org_role", OrgRole);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ProjectRole>("project_role", ProjectRole);
            writer.WriteGuidValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
