// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RegionResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether this region is used by default in new projects.</summary>
        public bool? Default { get; set; }
        /// <summary>The geographical latitude (approximate) for the region. Empty if unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeoLat { get; set; }
#nullable restore
#else
        public string GeoLat { get; set; }
#endif
        /// <summary>The geographical longitude (approximate) for the region. Empty if unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeoLong { get; set; }
#nullable restore
#else
        public string GeoLong { get; set; }
#endif
        /// <summary>A short description of the region.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The region ID as used in other API endpoints</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegionId { get; set; }
#nullable restore
#else
        public string RegionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.RegionResponse"/> and sets the default values.
        /// </summary>
        public RegionResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.RegionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.RegionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.RegionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default", n => { Default = n.GetBoolValue(); } },
                { "geo_lat", n => { GeoLat = n.GetStringValue(); } },
                { "geo_long", n => { GeoLong = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "region_id", n => { RegionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("default", Default);
            writer.WriteStringValue("geo_lat", GeoLat);
            writer.WriteStringValue("geo_long", GeoLong);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("region_id", RegionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
