// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>
    /// A branch-effective trigger that invokes a Function after a successfulupload matching its exact bucket and optional object-key prefix.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StorageObjectCreatedTrigger : IParsable
    {
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>Path passed to the target Function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionPath { get; set; }
#nullable restore
#else
        public string FunctionPath { get; set; }
#endif
        /// <summary>The branch-local Function slug resolved when an invocation is consumed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionSlug { get; set; }
#nullable restore
#else
        public string FunctionSlug { get; set; }
#endif
        /// <summary>True when the effective configuration was authored on an ancestor branch.</summary>
        public bool? Inherited { get; set; }
        /// <summary>Human-readable trigger name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The public `branch_id` of the branch that authored the effective configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceBranchId { get; set; }
#nullable restore
#else
        public string SourceBranchId { get; set; }
#endif
        /// <summary>Matches successful uploads to one exact bucket and, when configured, anobject-key prefix. The Function receives a JSON request body with`type` set to `storage_object_created` and a `data` object containingexactly `bucket_name` and `object_key`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerStorageObjectCreated? StorageObjectCreated { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerStorageObjectCreated StorageObjectCreated { get; set; }
#endif
        /// <summary>Opaque, server-minted project-wide trigger identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerId { get; set; }
#nullable restore
#else
        public string TriggerId { get; set; }
#endif
        /// <summary>Trigger type discriminator.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.StorageObjectCreatedType? Type { get; set; }
        /// <summary>Monotonic configuration version.</summary>
        public long? Version { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.StorageObjectCreatedTrigger"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.StorageObjectCreatedTrigger CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.StorageObjectCreatedTrigger();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "function_path", n => { FunctionPath = n.GetStringValue(); } },
                { "function_slug", n => { FunctionSlug = n.GetStringValue(); } },
                { "inherited", n => { Inherited = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "source_branch_id", n => { SourceBranchId = n.GetStringValue(); } },
                { "storage_object_created", n => { StorageObjectCreated = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerStorageObjectCreated>(global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerStorageObjectCreated.CreateFromDiscriminatorValue); } },
                { "trigger_id", n => { TriggerId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.StorageObjectCreatedType>(); } },
                { "version", n => { Version = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("function_path", FunctionPath);
            writer.WriteStringValue("function_slug", FunctionSlug);
            writer.WriteBoolValue("inherited", Inherited);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("source_branch_id", SourceBranchId);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerStorageObjectCreated>("storage_object_created", StorageObjectCreated);
            writer.WriteStringValue("trigger_id", TriggerId);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.StorageObjectCreatedType>("type", Type);
            writer.WriteLongValue("version", Version);
        }
    }
}
#pragma warning restore CS0618
