// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Neon.OpenApiClient.Models
{
    /// <summary>
    /// Trigger creation payload discriminated by `type`. The only currentlysupported trigger type is `schedule`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TriggerCreateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether future occurrences should be scheduled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Path passed to the target Function. Defaults to `/`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionPath { get; set; }
#nullable restore
#else
        public string FunctionPath { get; set; }
#endif
        /// <summary>The branch-local Function slug to invoke.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionSlug { get; set; }
#nullable restore
#else
        public string FunctionSlug { get; set; }
#endif
        /// <summary>Human-readable name, unique among triggers visible on the branch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A numeric five-field cron schedule interpreted in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerSchedule? Schedule { get; set; }
#nullable restore
#else
        public global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerSchedule Schedule { get; set; }
#endif
        /// <summary>Trigger type discriminator.</summary>
        public global::Soenneker.Neon.OpenApiClient.Models.ScheduleType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Models.TriggerCreateRequest"/> and sets the default values.
        /// </summary>
        public TriggerCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Enabled = true;
            FunctionPath = "/";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.TriggerCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Neon.OpenApiClient.Models.TriggerCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Neon.OpenApiClient.Models.TriggerCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "function_path", n => { FunctionPath = n.GetStringValue(); } },
                { "function_slug", n => { FunctionSlug = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "schedule", n => { Schedule = n.GetObjectValue<global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerSchedule>(global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerSchedule.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ScheduleType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("function_path", FunctionPath);
            writer.WriteStringValue("function_slug", FunctionSlug);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Neon.OpenApiClient.Models.FunctionTriggerSchedule>("schedule", Schedule);
            writer.WriteEnumValue<global::Soenneker.Neon.OpenApiClient.Models.ScheduleType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
