// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Neon.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Test
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{projectId}\branches\{branchId}\auth\email_provider\test
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Test.TestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/branches/{branchId}/auth/email_provider/test", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Test.TestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{projectId}/branches/{branchId}/auth/email_provider/test", rawUrl)
        {
        }
        /// <summary>
        /// Sends a test email using the branch&apos;s already-saved custom SMTP configuration. Only the`recipient_email` is provided — the stored SMTP settings and password are used server-side,so the caller does not need to re-supply (or be able to read) the password. This avoids theGET response&apos;s masked password being sent back, which would fail SMTP authentication.Requires a configured custom SMTP provider on a Better Auth integration. A shared provider,a missing configuration, or a non-Better-Auth integration is rejected.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthTestEmailResponse"/></returns>
        /// <param name="body">Request to test the branch&apos;s saved email provider. Only the recipient is supplied; the storedSMTP settings and password are used server-side.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Neon.OpenApiClient.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthTestEmailResponse?> PostAsync(global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthEmailProviderTestRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthTestEmailResponse> PostAsync(global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthEmailProviderTestRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Neon.OpenApiClient.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthTestEmailResponse>(requestInfo, global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthTestEmailResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Sends a test email using the branch&apos;s already-saved custom SMTP configuration. Only the`recipient_email` is provided — the stored SMTP settings and password are used server-side,so the caller does not need to re-supply (or be able to read) the password. This avoids theGET response&apos;s masked password being sent back, which would fail SMTP authentication.Requires a configured custom SMTP provider on a Better Auth integration. A shared provider,a missing configuration, or a non-Better-Auth integration is rejected.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request to test the branch&apos;s saved email provider. Only the recipient is supplied; the storedSMTP settings and password are used server-side.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthEmailProviderTestRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Neon.OpenApiClient.Models.SendNeonAuthEmailProviderTestRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Test.TestRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Test.TestRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Neon.OpenApiClient.Projects.Item.Branches.Item.Auth.Email_provider.Test.TestRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
